#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "woodpecker"
name = "Woodpecker"
description.en = "CI engine with great extensibility integrated with GitHub, GitLab, Gitea..."
description.fr = "Outil d'intégration continue extensible intégrable avec GitHub, GitLab, Gitea..."

version = "3.16.0~ynh1"

maintainers = [ "Salamandar" ]

[upstream]
license = "Apache-2.0"
website = "https://woodpecker-ci.org"
admindoc = "https://woodpecker-ci.org/docs/administration"
userdoc = "https://woodpecker-ci.org/docs/intro"
code = "https://github.com/woodpecker-ci/woodpecker"
cpe = "cpe:2.3:a:woodpecker-ci:woodpecker"
fund = "https://opencollective.com/woodpecker-ci"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "0M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/woodpecker"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.forge_type]
    ask.en = "Select the kind of forge you're connecting Woodpecker to"
    ask.fr = "Sélectionnez le type de forge à laquelle vous connectez Woodpecker"
    type = "select"
    choices.github = "Github"
    choices.gitlab = "Gitlab"
    choices.gitea = "Gitea / Forgejo"
    choices.bitbucket = "Bitbucket"
    default = "github"

    [install.forge_url]
    ask.en = "Provide the forge URL"
    ask.fr = "Entrez l'URL de la forge"
    type = "string"
    default = "https://myforge.tld"
    help.en = "Useless for Bitbucket and Github.com."
    help.fr = "Inutile pour Bitbucket et Github.com."

    [install.forge_client]
    ask.en = "Provide the forge OAuth Client ID"
    ask.fr = "Entrez l'ID de client OAuth de la forge"
    type = "string"
    default = ""

    [install.forge_secret]
    ask.en = "Provide the forge OAuth secret"
    ask.fr = "Entrez le secret OAuth de la forge"
    type = "string"
    default = ""

    [install.admin]
    type = "user"

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/woodpecker-ci/woodpecker/releases/download/v3.16.0/woodpecker-server_linux_amd64.tar.gz"
    amd64.sha256 = "c8e46545a6b68959d5196b8f998403528efb93f12411093967efd914116f2104"

    arm64.url = "https://github.com/woodpecker-ci/woodpecker/releases/download/v3.16.0/woodpecker-server_linux_arm64.tar.gz"
    arm64.sha256 = "80a31312a883387914191946e84afeb563d35e94534af22ad6f96acfc3f4eb10"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "woodpecker-server_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "woodpecker-server_linux_arm64.tar.gz"

    in_subdir = false

    [resources.sources.agent]
    amd64.url = "https://github.com/woodpecker-ci/woodpecker/releases/download/v3.16.0/woodpecker-agent_linux_amd64.tar.gz"
    amd64.sha256 = "063f865bb63e694090663cd73159c8c3a463641640d93f01977e2e6c12320e59"

    arm64.url = "https://github.com/woodpecker-ci/woodpecker/releases/download/v3.16.0/woodpecker-agent_linux_arm64.tar.gz"
    arm64.sha256 = "9566bd95cc98876653f05db079f1f410b105922f9ee9eac6f6c60227eaf28826"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "woodpecker-agent_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "woodpecker-agent_linux_arm64.tar.gz"

    in_subdir = false

    [resources.system_user]
    
    [resources.install_dir]
    
    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    
    main.default = 8000
    grpc.default = 9000
    healthcheck.default = 3002
    
    [resources.apt]
    packages = [ "git", "git-lfs", "postgresql" ]

    [resources.database]
    type = "postgresql"
