#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "woodpecker"
name = "Woodpecker"
description.en = "CI engine with great extensibility integrated with GitHub, GitLab, Gitea..."
description.fr = "Outil d'intégration continue extensible intégrable avec GitHub, GitLab, Gitea..."

version = "2.8.1~ynh1"

maintainers = [ "Salamandar" ]

[upstream]
license = "Apache-2.0"
website = "https://woodpecker-ci.org"
admindoc = "https://woodpecker-ci.org/docs/administration"
userdoc = "https://woodpecker-ci.org/docs/intro"
code = "https://github.com/woodpecker-ci/woodpecker"
cpe = "cpe:2.3:a:woodpecker-ci:woodpecker"

fund = "https://opencollective.com/woodpecker-ci"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "0M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/woodpecker"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.forge_type]
    ask.en = "Select the kind of forge you're connecting Woodpecker to"
    ask.fr = "Sélectionnez le type de forge à laquelle vous connectez Woodpecker"
    type = "select"
    choices.github = "Github"
    choices.gitlab = "Gitlab"
    choices.gitea = "Gitea / Forgejo"
    choices.bitbucket = "Bitbucket"
    default = "github"

    [install.forge_url]
    ask.en = "Provide the forge URL"
    ask.fr = "Entrez l'URL de la forge"
    type = "string"
    default = "https://myforge.tld"
    help.en = "Useless for Bitbucket and Github.com."
    help.fr = "Inutile pour Bitbucket et Github.com."

    [install.forge_client]
    ask.en = "Provide the forge OAuth Client ID"
    ask.fr = "Entrez l'ID de client OAuth de la forge"
    type = "string"
    default = ""

    [install.forge_secret]
    ask.en = "Provide the forge OAuth secret"
    ask.fr = "Entrez le secret OAuth de la forge"
    type = "string"
    default = ""

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/woodpecker-ci/woodpecker/releases/download/v2.8.1/woodpecker-server_linux_amd64.tar.gz"
    amd64.sha256 = "fd6e7f0e6d54e0959fb08acd80e187204da916c44d2069e92032445c53c5a3a0"

    arm64.url = "https://github.com/woodpecker-ci/woodpecker/releases/download/v2.8.1/woodpecker-server_linux_arm64.tar.gz"
    arm64.sha256 = "f99bdc47d7a8ea7dfebd6b23d19fbcde32596a30d518351bd512228f6e86426e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "woodpecker-server_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "woodpecker-server_linux_arm64.tar.gz"

    in_subdir = false

[resources.system_user]

[resources.install_dir]

[resources.data_dir]

[resources.permissions]
main.url = "/"

[resources.ports]

main.default = 8000
grpc.default = 9000

[resources.apt]
packages = [ "postgresql" ]

[resources.database]
type = "postgresql"
