#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # exclude = ["install.private", "install.multi"]
    # The test IDs to be used in only/exclude statements are:
    # * install.root
    # * install.subdir
    # * install.nourl
    # * install.multi
    # * backup_restore
    # * upgrade
    # * upgrade.someCommitId
    # * change_url
    # NB: you should NOT need this except if you really have a good reason...
    
    # For special usecases, sometimes you need to setup other things on the machine
    # prior to installing the app (such as installing another app)
    # (Remove this key entirely if not needed)
    # preinstall = """
    # sudo yunohost app install foobar
    # sudo yunohost user list
    # """
    args.forge_type = "github"
    args.forge_url = "https://github.com"
    args.forge_client = "dummy client"
    args.forge_secret = "dummy secret"

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3deb546fd3eb6f0dc67292533d05d36abfa5b648.name = "Upgrade from 3.0.1~ynh1"
