#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    args.forge_type = "github"
    args.forge_url = "https://github.com"
    args.forge_client = "dummy client"
    args.forge_secret = "dummy secret"

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3deb546fd3eb6f0dc67292533d05d36abfa5b648.name = "Upgrade from 3.0.1~ynh1"
