#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ls -lah "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Woodpecker CI server" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
touch "/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

path_no_trailing_slash=${path%/}
_woodpecker_set_forge_config

ynh_config_add --template="woodpecker-server.conf" --destination="$install_dir/woodpecker-server.conf"

chmod 400 "$install_dir/woodpecker-server.conf"
chown "$app:$app" "$install_dir/woodpecker-server.conf"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
