#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATABASE
#=================================================
ynh_script_progression "Restoring the database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

ynh_restore "/etc/systemd/system/$app-agent.service"
systemctl enable "$app-agent.service" --quiet

yunohost service add "$app" --description="Woodpecker CI server" --log="/var/log/$app/$app.log"
yunohost service add "$app-agent" --description="Woodpecker CI agent" --log="/var/log/$app/$app-agent.log"

# Create log file before logrotate
mkdir -p "/var/log/$app"
touch "/var/log/$app/$app.log"
touch "/var/log/$app/$app-agent.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --wait_until="starting Woodpecker server with version"
ynh_systemctl --service="$app-agent" --action="start" #--wait_until="starting Woodpecker agent with version"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
