#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key="key" --value="$(ynh_string_random --length=32)"
key=$(ynh_app_setting_get --key="key")

ynh_app_setting_set_default --key="admin" --value="$(ynh_user_list | head -n1)"
admin=$(ynh_app_setting_get --key="admin")

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd services..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-agent" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/agent" --source_id="agent"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service="$app-agent" --template="woodpecker-agent.service"

yunohost service add "$app" --description="Woodpecker CI server" --log="/var/log/$app/$app.log"
yunohost service add "$app-agent" --description="Woodpecker CI agent" --log="/var/log/$app/$app-agent.log"

ynh_config_add_logrotate

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

path_no_trailing_slash=${path%/}
_woodpecker_set_forge_config

ynh_config_add --template="woodpecker-server.conf" --destination="$install_dir/woodpecker-server.conf"
ynh_config_add --template="woodpecker-agent.env" --destination="$install_dir/agent/woodpecker-agent.env"

chmod 400 "$install_dir/woodpecker-server.conf"
chown "$app:$app" "$install_dir/woodpecker-server.conf"
chmod 400 "$install_dir/agent/woodpecker-agent.env"
chown "$app:$app" "$install_dir/agent/woodpecker-agent.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="starting Woodpecker server with version"
ynh_systemctl --service="$app-agent" --action="start" #--wait_until="starting Woodpecker agent with version"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
